### ISSUE TITLE
Devra Bodganovich 2023 - Wrong Title

### ISSUE THREAD

**Issue by DrJest** [dedo1911/ingress-plus#54]
https://ingress.plus/api/files/i37o5ykupb5voix/vwgxrlrys8nd3mq/character_devra_bogdanovich_2023_sKcBa1uHgL.png
This has the title "Devra Bogdanovich" instead of "Devra Bogdanovich 2023"

**Comment by InvestigateXM** [comment]
Fixed, thanks :)
